name: first
on: [workflow_dispatch,push]
jobs:
    getcode:
        runs-on: ubuntu-latest
        steps:
            - name: getcode
              uses: actions/checkout@v4
            - name: install dependencies
              run: npm ci
    npm:
        runs-on: ubuntu-latest
        steps:
            - name: npm
              run: npm run build
    lint:
        needs: npm
        runs-on: ubuntu-latest
        steps:
            - name: lint
              run: npm run lint
    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - name: test
              run: npm run test
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: deploy
              run: npm run deploy    
              