name: first
on: [workflow_dispatch,push]
jobs:
    npm:
        runs-on: ubuntu-latest
        steps:
            - name: npm
              run: npm run build
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: lint
              run: npm run lint
    test:
        runs-on: ubuntu-latest
        steps:
            - name: test
              run: npm run test
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: deploy
              run: npm run deploy    
              