name: first
on: [workflow_dispatch,push]
jobs:
    getcode:
        runs-on: ubuntu-latest
        steps:
            - name: getcode
              uses: actions/checkout@v4
            - name: install dependencies
              run: npm ci
            - name: npm
              run: npm run lint
            - name: npm
              run: npm run test
            - name: npm
              run: npm run deploy


