name: first
on:
  push:
    branches:
      - main
jobs:
    getcode:
        runs-on: ubuntu-latest
        steps:
            - name: getcode
              uses: actions/checkout@v4
            - name: install dependencies
              run: npm ci
            - name: lint
              run: npm run lint
            - name: test
              run: npm run test
            - name: deploy
              run: echo "deploying"


